
DROP TABLE IF EXISTS TBL_REFERENCE;
CREATE TABLE TBL_REFERENCE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(50) NOT NULL,
    FULL_ADDRESS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    BUSINESS_OCCUPATION VARCHAR(100) NOT NULL
 );

INSERT INTO TBL_REFERENCE (FULL_NAME, FULL_ADDRESS, EMAIL, BUSINESS_OCCUPATION ) VALUES
    ('Moses Wallace', 'Kampala, Uganda', 'moses.wallace@gmail.com', 'Software Engineer');




