/* Drop or Create reference table */
DROP TABLE IF EXISTS TBL_REFERENCE;
CREATE TABLE TBL_REFERENCE (
    ID_REFERENCE INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(50) NOT NULL,
    FULL_ADDRESS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    BUSINESS_OCCUPATION VARCHAR(100) NOT NULL
 );

/* Drop or Create publication table */
DROP TABLE IF EXISTS TBL_PUBLICATION;
CREATE TABLE TBL_PUBLICATION (
    ID_PUBLICATION INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    PUBLISHER VARCHAR(200) NOT NULL,
    DATE_PUBLISHED DATE NOT NULL,
    CITY_PUBLISHED VARCHAR(40) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL
 );

/* Drop or Create relative table */
DROP TABLE IF EXISTS TBL_RELATIVE;
CREATE TABLE TBL_RELATIVE (
    ID_RELATIVE INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    RELATIONSHIP VARCHAR(20) NOT NULL,
    INTERNATIONAL_ORGANIZATION VARCHAR(200) NOT NULL
 );

 /* Drop or Create dependent table */
DROP TABLE IF EXISTS TBL_DEPENDENT;
CREATE TABLE TBL_DEPENDENT (
    ID_DEPENDENT INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    RELATIONSHIP VARCHAR(20) NOT NULL
 );


/* Insert data into reference table */
INSERT INTO TBL_REFERENCE (FULL_NAME, FULL_ADDRESS, EMAIL, BUSINESS_OCCUPATION ) VALUES
    ('Moses Wallace', 'Kampala, Uganda', 'moses.wallace@gmail.com', 'Software Engineer');


/* Insert data into publication table */
INSERT INTO TBL_PUBLICATION (TITLE, PUBLISHER, DATE_PUBLISHED, CITY_PUBLISHED, COUNTRY ) VALUES
    ('Algorithms in the Oil and Gas industry', 'Oxford Press Ltd', '2019-09-12', 'Kampala', 'Uganda');


/* Insert data into relative table */
INSERT INTO TBL_RELATIVE (NAME, RELATIONSHIP, INTERNATIONAL_ORGANIZATION ) VALUES
    ('Daniel Alves', 'Brother', 'UNEPI');




